# Attempts to install SCS in Python 2.7 and Python 3.3 on both 64- and 32-bit Windows.
# (initial copy from appveyor.yml in ECOS project)
environment:
    matrix:
        - PYVER: 2.7
          PYLOC: python27
        - PYVER: 3.4
          PYLOC: python34

platform:
    - x86
    - x64

install:
    - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:\get-pip.py')
    - C:\%PYLOC%\python C:\get-pip.py
    - C:\%PYLOC%\Scripts\pip.exe install conda==3.7.0 # remove version when 'activate.bat missing' bug fixed
    - C:\%PYLOC%\Scripts\conda.exe init
    - C:\%PYLOC%\Scripts\conda.exe create -n testenv --yes --quiet python=%PYVER% numpy scipy nose setuptools

build_script:
    - cd python
    - C:\%PYLOC%\envs\testenv\python.exe setup.py install
    - cd ..

test_script:
    - cd python
    - C:\%PYLOC%\envs\testenv\Scripts\nosetests.exe test_scs_basic.py test_scs_rand.py
    - cd ..
